{% set name = "bioregistry" %}
{% set version = "0.10.108" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bioregistry-{{ version }}.tar.gz
  sha256: d43eaa26efb64b547259905e4b9fc47fdcd0aeba4d5e920959aa0cf87b016e2e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  entry_points:
    - bioregistry = bioregistry.cli:main

requirements:
  host:
    - python >=3.8
    - setuptools
    - wheel
    - pip
  run:
    - python >=3.8
    - requests
    - tqdm
    - pystow >=0.1.13
    - click
    - more-click >=0.1.2
    - pydantic
    - curies >=0.7.0

test:
  imports:
    - bioregistry
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/biopragmatics/bioregistry
  summary: Integrated registry of biological databases and nomenclatures
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - isuruf
    - dillonroach
